ALTER TABLE license ADD COLUMN IF NOT EXISTS machine_id VARCHAR(128) NULL AFTER expire_time;
ALTER TABLE license ADD COLUMN IF NOT EXISTS signature VARCHAR(2048) NULL AFTER machine_id;
ALTER TABLE license MODIFY COLUMN status TINYINT DEFAULT 1;
